# Generated by Django 4.1.7 on 2023-06-08 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 8, 8, 52, 27, 43495, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
