# Generated by Django 4.1.7 on 2023-06-14 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=140)),
                ('message', models.CharField(max_length=500)),
                ('email1', models.EmailField(max_length=100)),
                ('phone1', models.CharField(max_length=13)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
