# Generated by Django 4.1.7 on 2023-06-09 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=200)),
                ('nick', models.CharField(default=False, max_length=80)),
                ('email', models.EmailField(default=False, max_length=120)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default=False, max_length=10)),
                ('number', models.CharField(default=False, max_length=40)),
                ('cvc', models.CharField(default=False, max_length=6)),
                ('expiry', models.DateField()),
                ('current', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
