# Generated by Django 4.1.7 on 2023-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_payment_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
