# Generated by Django 4.1.7 on 2023-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=False, max_length=100)),
                ('username', models.CharField(default=False, max_length=140)),
                ('password', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
